version: "3.8"
services:
  sleekfolio:
    build:
      context: sleekfolio
    environment:
      - VIRTUAL_HOST=folio.sleekforum.com
      - VIRTUAL_PROTO=uwsgi
      - LETSENCRYPT_HOST=folio.sleekforum.com
    env_file:
      - ./sleekfolio/configs/env/postgres.env
    restart: unless-stopped
    volumes:
      - /var/www/sleekfolio/backup:/var/lib/postgres/data
      - ./sleekfolio/configs/nginx/conf.d:/etc/nginx/conf.d
      - ./sleekfolio/src:/srv/http/sleekfolio:z
    networks:
      - db
      - webserver
    depends_on:
      - postgres

  sleekforum:
    build:
      context: sleekforum/src
      args:
        sleekforum_environment: production
    restart: unless-stopped
    volumes:
      - "./sleekforum/src:/srv/http/sleekforum:z"
    environment:
      - SSL_POLICY=Mozilla-Modern
      - SLEEKFORUM_DB_HOST=postgres
    env_file:
      - ./sleekforum/configs/env/nginx.env
      - ./sleekforum/configs/env/sleekforum.env
    networks:
      - cache
      - db
      - webserver
    depends_on:
      - postgres
      - nginx-lets-encrypt

  postgres:
    image: postgres
    networks:
      - db
      - pgadmin
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - VIRTUAL_HOST=pgadmin.sleekforum.com
      - LETSENCRYPT_HOST=pgadmin.sleekforum.com
      - VIRTUAL_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=adepeter26@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adepeter
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - "pgadmin4:/var/lib/pgadmin"
      - "pgadmin:/root/.pgadmin"
    networks:
      - pgadmin
      - webserver
    depends_on:
      - postgres
    ports:
      - "5050:5050"

  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - webserver
    restart: always
    environment:
      - ENABLE_IPV6=true
    volumes:
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./sleeknginx/conf.d:/etc/nginx/conf.d"
      - "./sleeknginx/vhost.d:/etc/nginx/vhost.d"
      - "./sleekforum/src/static:/srv/ftp/sleekforum/static:z"
      - "./sleekforum/src/media:/srv/ftp/sleekforum/media:z"
      - "./sleekfolio/src/static:/srv/ftp/sleekfolio/static:z"
      - "./sleekfolio/src/media:/srv/ftp/sleekfolio/media:z"
    ports:
      - "80:80"
      - "443:443"

  nginx-lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - webserver
    env_file:
      - ./sleekforum/configs/env/companion.env
    depends_on:
      - nginx-proxy
    volumes:
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./sleeknginx/vhost.d:/etc/nginx/vhost.d"

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - cache
    volumes:
      - cached_data:/data


networks:
  cache:
  db:
  pgadmin:
  webserver:

volumes:
  cached_data:
  nginx-certs:
  nginx-html:
  pg_data:
  pgadmin4:
  pgadmin: