version: "3.8"
services:
  sleekfolio:
    build:
      context: .
    environment:
      - POSTGRES_HOST=localhost
    restart: unless-stopped
    env_file:
      - ./configs/env/postgres.env
      - ./configs/env/sleekfolio.env
      - ./configs/env/nginx.env
    volumes:
    - /var/www/sleekfolio/backup:/var/lib/postgres/data
    - ./configs/nginx/conf.d:/etc/nginx/conf.d
    - ./src:/srv/http/sleekfolio
    networks:
      - webserver

  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - webserver
    restart: always
    environment:
      - ENABLE_IPV6=true
    volumes:
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
      - "443:443"

networks:
  webserver:

volumes:
  nginx-certs:
  nginx-html: